tag: dev

api:
  replicaCount: 1
  image: okteto.dev/api

frontend:
  replicaCount: 1
  image: okteto.dev/frontend

mongodb:
  password: "patate12345"
  database: "simulation"
  username: "my_user"
  
tomcat:
  tomcatUsername: admin
  tomcatPassword: admin
  tomcatAllowRemoteManagement: 1
  persistence:
    size: 3Gi